### ISSUE TITLE
Torch unable to use ORT because of opset version issue

### ISSUE THREAD

**Issue by chethanpk** [pytorch/ort#100]
torch-ort: 1.9.0
onnxruntime-training: 1.11
OS: Ubuntu 20.04

To reproduce, run below script with above libraries installed:
```
from datasets import load_dataset
raw_datasets = load_dataset("imdb")  
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")
def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)
tokenized_datasets = raw_datasets.map(tokenize_function, batched=True)
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))
full_train_dataset = tokenized_datasets["train"]
full_eval_dataset = tokenized_datasets["test"]
from transformers import AutoModelForSequenceClassification
model = AutoModelForSequenceClassification.from_pretrained("bert-base-cased", num_labels=2)
from torch_ort import ORTModule
model = ORTModule(model)
from transformers import TrainingArguments
training_args = TrainingArguments("test_trainer")
training_args.per_device_train_batch_size = 2
training_args.num_train_epochs = 1
training_args.max_steps = 1
from transformers import Trainer
trainer = Trainer(model=model, args=training_args, train_dataset=small_train_dataset, eval_dataset=small_eval_dataset)                                                                                             
```

I built the latest onnxruntime-training(1.11) wheel for cpu default and installed torch-ort using it. The ortmodule is trying to export the model with opset version of 14, which is returning as unsupported and my pytorch script is ending up using torch backend and ignoring ORT. I had the script previously working with an older version of onnxruntime-training(1.10).

I modify the ortmodule to use OneDNN EP. I am unable to utilize this flow because of the above issue. Is there a way to prevent the module from exporting it to OPSET 14 by default?

Here is the error log:
```
Traceback (most recent call last):
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_utils.py", line 254, in get_exception_as_string
    raise exception
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_training_manager.py", line 223, in forward
    build_gradient_graph = self._export_model(*inputs, **kwargs)
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 321, in _export_model
    self._onnx_models.exported_model = self._get_exported_model(
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 391, in _get_exported_model
    raise wrap_exception(ORTModuleONNXModelException,
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_fallback_exceptions.py", line 72, in wrap_exception
    raise new_exception(raised_exception) from raised_exception
onnxruntime.training.ortmodule._fallback_exceptions.ORTModuleONNXModelException: There was an error while exporting the PyTorch model to ONNX:

Traceback (most recent call last):
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_utils.py", line 254, in get_exception_as_string
    raise exception
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/onnxruntime/training/ortmodule/_graph_execution_manager.py", line 385, in _get_exported_model
    torch.onnx.export(self._flattened_module,
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/torch/onnx/utils.py", line 672, in _export
    _set_opset_version(opset_version)
  File "/home/mtc/code/chethan/vitualenv/lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 783, in _set_opset_version
    raise ValueError("Unsupported ONNX opset version: " + str(opset_version))
ValueError: Unsupported ONNX opset version: 14
```

**Comment by baijumeswani** [comment]
I think if you updated the pytorch version you're using, you might be able to resolve the error you're seeing. What version of pytorch are you currently using?

To answer your question about controlling the opset version:
You can control the onnx opset version that is being used by assigning the environment variable (`ORTMODULE_ONNX_OPSET_VERSION`) to the opset version you would like to use.

**Comment by chethanpk** [comment]
Updating Pytorch worked for me, thanks.
Will make a note of the environment variable.
